languages_mapping:
  two_letters_code:
    pt-BR: pt_BR
files:
  - source: /lending/locale/main.pot
    translation: /lending/locale/%two_letters_code%.po
pull_request_title: "chore: sync translations from crowdin"
pull_request_labels:
  - translation
commit_message: "chore: %language% translations"
append_commit_message: false